{% set version = '0.1.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-yarrr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/yarrr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yarrr/yarrr_{{ version }}.tar.gz
  sha256: 8515ee101e5d354e9b06fc1f1867ff0bdbe6f973a359bb94eb8a45d28f5ca888

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-bayesfactor
    - r-circlize
    - r-jpeg
  run:
    - r-base
    - r-bayesfactor
    - r-circlize
    - r-jpeg

test:
  commands:
    - $R -e "library('yarrr')"           # [not win]
    - "\"%R%\" -e \"library('yarrr')\""  # [win]

about:
  home: www.thepiratesguidetor.com
  license: GPL-2.0-only
  summary: 'Contains a mixture of functions and data sets referred to in the introductory e-book
    "YaRrr!: The Pirate''s Guide to R". The latest version of the e-book is available
    for free at <https://www.thepiratesguidetor.com>.'
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - apcamargo
