appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pibV6WIhcFwJ94c4q4RPlRYDLKmfBLqjw+UfgRjstx7JM4NwQlCx9weegbdJLiAntQrRqpIQ12CywK3hPRDorCQMBoqKjTHgrYNZZSRxovvZ0Udlibzpr5SOU2ucEq+R3ipAK56TlTYx1e+vgpsXBBCCQ9P97s4gX1JZWwSo+yXMZkUDBVFoxIv7em1XqxPvlIg0kvSKTjUgq7qr8894t2LBHvCo37aDuZblhp94C0X7XPyb8Rw2bhYWHCwxsYE+/t51JnbNrNGnw/tWvlugzcWqll4YjEm241kvJH76eUNrrl91Ec6VWmRtCY5TWCP2FoDdq6kQzJxNfJuU2fnHG4Q78C9esJn+v5DB7TETl1JrcycCJezNMLNcNC/xSPCmh6LUGvFVOJymNCYcPhXbVYGhsIfktxngQsSzZZ6cbglsfpKcwcm8GMRlcrxnOMxOMb2fWmvfkJyoHNZI0LDZjygYVyKGeu13bs9ws3QuY13bGcm/co7wmyBYeCbSMhF8OS/rcDk/96xNGRaN/2vuddRw9z1dX8s9snBF9ULswsvGuxCsgXYdpv+F0c5euQOyLu9qaG1M/fGoinMOYuLjBoB5rnTcpNc+E41oT8XOfKYYlnYfzM4ei1cXiWf5AWmJrMoHG+ezBH9mjbhuX5rhykCecW+UyN3yqj4wBxPhe/A=
